<?php
$page_title = 'Generate Payslips';
$active_nav = 'payslip';
$depth      = '../../';

$success = '';
$error   = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['generate'])) {
    $period = $_POST['period'] ?? '';
    if (empty($period)) {
        $error = 'Please select a verified payroll period.';
    } else {
        $success = 'Payslips generated successfully for all 135 employees — ' . htmlspecialchars($period) . '. Employees can now view and download their payslips.';
    }
}

require_once $depth . 'includes/header.php';
?>

<div class="breadcrumb">
    <a href="dashboard.php">Finance</a><span>/</span><span>Generate Payslips</span>
</div>

<div class="page-header d-flex justify-between align-center">
    <div>
        <h1>Generate Payslips</h1>
        <p>Generate electronic payslips for all employees after payroll verification.</p>
    </div>
    <a href="verify_payroll.php" class="btn btn-secondary">
        <i class="fas fa-check-double"></i> Verify Payroll First
    </a>
</div>

<?php if ($success): ?>
<div class="alert alert-success"><i class="fas fa-check-circle"></i> <?= $success ?></div>
<?php endif; ?>
<?php if ($error): ?>
<div class="alert alert-danger"><i class="fas fa-exclamation-circle"></i> <?= $error ?></div>
<?php endif; ?>

<!-- Generate Form -->
<div class="card mb-3">
    <div class="card-header">
        <h3><i class="fas fa-file-invoice-dollar" style="color:var(--primary);margin-right:8px"></i>Generate Payslips</h3>
    </div>
    <div class="card-body">
        <form method="POST" action="">
            <div class="form-row" style="align-items:flex-end;">
                <div class="form-group">
                    <label class="form-label">Select Verified Period <span style="color:var(--danger)">*</span></label>
                    <select name="period" class="form-control" required>
                        <option value="">-- Select Period --</option>
                        <option value="June 2023">June 2023 — ✅ Verified</option>
                        <option value="May 2023">May 2023 — ✅ Verified</option>
                        <option value="April 2023">April 2023 — ✅ Verified</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-label">Generate For</label>
                    <select name="scope" class="form-control">
                        <option value="all">All Employees (135)</option>
                        <option value="academic">Academic Staff Only</option>
                        <option value="admin">Administrative Staff Only</option>
                    </select>
                </div>
                <div class="form-group" style="padding-bottom:18px;">
                    <button type="submit" name="generate" class="btn btn-primary">
                        <i class="fas fa-file-invoice-dollar"></i> Generate Payslips
                    </button>
                </div>
            </div>
        </form>

        <!-- Prerequisite Info -->
        <div class="alert alert-info" style="margin-top:8px;">
            <i class="fas fa-info-circle"></i>
            <div>
                <strong>Prerequisites:</strong> Payroll must be <strong>verified and approved</strong> before payslips can be generated.
                Once generated, employees can view and download their payslips from their dashboard.
            </div>
        </div>
    </div>
</div>

<!-- Payslip Status by Period -->
<div class="card mb-3">
    <div class="card-header">
        <h3><i class="fas fa-history" style="color:var(--primary);margin-right:8px"></i>Payslip Generation History</h3>
    </div>
    <div class="card-body" style="padding:0">
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Period</th>
                        <th>Payroll Status</th>
                        <th>Payslips Generated</th>
                        <th>Generated On</th>
                        <th>Generated By</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $history = [
                        ['June 2023',     'Verified',   '135 / 135', '2023-06-23', 'Finance Officer', true],
                        ['May 2023',      'Verified',   '133 / 133', '2023-05-28', 'Finance Officer', true],
                        ['April 2023',    'Verified',   '130 / 130', '2023-04-28', 'Finance Officer', true],
                        ['March 2023',    'Verified',   '130 / 130', '2023-03-28', 'Finance Officer', true],
                        ['February 2023', 'Verified',   '128 / 128', '2023-02-25', 'Finance Officer', true],
                    ];
                    foreach ($history as $h): ?>
                    <tr>
                        <td><strong><?= $h[0] ?></strong></td>
                        <td><span class="badge badge-success"><?= $h[1] ?></span></td>
                        <td><span class="badge badge-primary"><?= $h[2] ?></span></td>
                        <td class="text-muted"><?= $h[3] ?></td>
                        <td class="text-muted"><?= $h[4] ?></td>
                        <td>
                            <button class="btn btn-secondary btn-sm" title="View Payslips">
                                <i class="fas fa-eye"></i> View
                            </button>
                            <button class="btn btn-primary btn-sm" title="Download All">
                                <i class="fas fa-download"></i> Download All
                            </button>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Sample Payslip Preview -->
<div class="card">
    <div class="card-header">
        <h3><i class="fas fa-eye" style="color:var(--primary);margin-right:8px"></i>Sample Payslip Preview — June 2023</h3>
        <button class="btn btn-primary btn-sm" onclick="openModal('payslipPreview')">
            <i class="fas fa-expand"></i> Full Preview
        </button>
    </div>
    <div class="card-body">
        <div style="max-width:560px;margin:0 auto;border:1px solid var(--gray-200);border-radius:var(--radius);overflow:hidden;">
            <!-- Payslip Header -->
            <div style="background:var(--primary);color:white;padding:20px;text-align:center;">
                <div style="font-size:1.5rem;font-weight:900;letter-spacing:-1px;">BiT</div>
                <div style="font-weight:700;font-size:1rem;">Bahir Dar Institute of Technology</div>
                <div style="font-size:0.85rem;opacity:0.85;">PAYSLIP — JUNE 2023</div>
            </div>
            <!-- Employee Info -->
            <div style="padding:16px;background:var(--bg-light);display:grid;grid-template-columns:1fr 1fr;gap:12px;">
                <div><p style="font-size:0.72rem;color:var(--gray-400);margin:0;">Employee Name</p><p style="font-weight:600;margin:0;">Admasu Dejene</p></div>
                <div><p style="font-size:0.72rem;color:var(--gray-400);margin:0;">Employee ID</p><p style="font-weight:600;margin:0;">EMP-101</p></div>
                <div><p style="font-size:0.72rem;color:var(--gray-400);margin:0;">Department</p><p style="font-weight:600;margin:0;">Faculty of Computing</p></div>
                <div><p style="font-size:0.72rem;color:var(--gray-400);margin:0;">Position</p><p style="font-weight:600;margin:0;">Lecturer</p></div>
            </div>
            <!-- Earnings & Deductions -->
            <div style="padding:16px;">
                <table style="width:100%;font-size:0.85rem;border-collapse:collapse;">
                    <tr style="background:var(--bg-light);"><th style="padding:8px;text-align:left;color:var(--primary);">Earnings</th><th style="padding:8px;text-align:right;color:var(--primary);">ETB</th></tr>
                    <tr><td style="padding:7px 8px;">Basic Salary</td><td style="padding:7px 8px;text-align:right;">12,500.00</td></tr>
                    <tr><td style="padding:7px 8px;">Housing Allowance</td><td style="padding:7px 8px;text-align:right;">1,000.00</td></tr>
                    <tr><td style="padding:7px 8px;">Transport Allowance</td><td style="padding:7px 8px;text-align:right;">500.00</td></tr>
                    <tr style="font-weight:700;background:var(--bg-light);"><td style="padding:8px;">Gross Salary</td><td style="padding:8px;text-align:right;color:var(--primary);">14,000.00</td></tr>
                    <tr style="background:var(--bg-light);"><th style="padding:8px;text-align:left;color:var(--danger);">Deductions</th><th style="padding:8px;text-align:right;color:var(--danger);">ETB</th></tr>
                    <tr><td style="padding:7px 8px;">Employee Pension (7%)</td><td style="padding:7px 8px;text-align:right;color:var(--warning);">875.00</td></tr>
                    <tr><td style="padding:7px 8px;">Income Tax</td><td style="padding:7px 8px;text-align:right;color:var(--danger);">1,948.25</td></tr>
                    <tr style="font-weight:700;background:var(--success-light);"><td style="padding:10px 8px;color:var(--success);">NET PAY</td><td style="padding:10px 8px;text-align:right;color:var(--success);font-size:1.1rem;">11,176.75</td></tr>
                </table>
                <p style="font-size:0.72rem;color:var(--gray-400);text-align:center;margin-top:10px;">Employer Pension (11%): ETB 1,375.00 — paid by BiT</p>
            </div>
        </div>
    </div>
</div>

<?php require_once $depth . 'includes/footer.php'; ?>
